export const levels = [
  // ================= 第一章：迷霧森林 (精準的步數控制與方向感) =================
  {
    id: 1,
    title: '1-1 窄門試煉',
    description: '學習最基本的移動，並繞過前方的障礙物。',
    // 🌟 新增：第一關的基礎教學
    tutorial: {
      message: '歡迎來到迷霧森林，年輕的法師！點擊右側的移動指令(move)繞開石頭，最後使用「attack()」擊敗怪物吧！',
      newCommand: 'attack'
    },
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 2, gridY: 5, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 6, gridY: 5, emoji: '👾', label: '弱小Bug' },
    obstacles: [{ x: 4, y: 5, type: 'rock' }],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveLeft', 'moveRight', 'attack'],
    restrictions: { maxBlocks: 7 },
    failMessages: {
      hitObstacle: '💥 哎呀！撞到石頭了，請先往上或往下繞開它。',
      maxStepsExceeded: '👣 走太多步囉！請找出最直接的路線。'
    },
    hint: '前方有石頭！試著移動(move)來繞過它，並攻擊(attack)怪物。',
    xpReward: 100,
    successMessage: '✨ 好的開始！你成功繞過了第一個障礙！',
  },
  {
    id: 2,
    title: '1-2 高牆阻擋',
    description: '面對更長的牆壁，你需要規劃更遠的路線。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 2, gridY: 2, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 6, gridY: 2, emoji: '👹', label: '紅眼怪物' },
    obstacles: [
      { x: 4, y: 1, type: 'wall' },
      { x: 4, y: 2, type: 'wall' },
      { x: 4, y: 3, type: 'wall' }
    ],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveLeft', 'moveRight', 'attack'],
    restrictions: { maxBlocks: 10 },
    failMessages: { hitObstacle: '💥 牆壁太高了跨不過去，必須從下面繞！' },
    hint: '這道牆很長，你需要先往下走好幾步才能繞過去。',
    xpReward: 120,
    successMessage: '✨ 路線清晰！再長的牆也擋不住你。',
  },
  {
    id: 3,
    title: '1-3 Ｚ字迷陣',
    description: '在錯綜複雜的岩石中穿梭。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 1, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 6, gridY: 6, emoji: '👻', label: '幽靈Bug' },
    obstacles: [
      { x: 3, y: 1, type: 'rock' }, { x: 3, y: 2, type: 'rock' },
      { x: 4, y: 5, type: 'rock' }, { x: 4, y: 6, type: 'rock' }
    ],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveLeft', 'moveRight', 'attack'],
    restrictions: { maxBlocks: 10 },
    failMessages: { maxStepsExceeded: '👣 步數耗盡！你沒有走在最短的 Z 字路線上。' },
    hint: '仔細觀察空隙，你的步數只夠你走最完美的路線。',
    xpReward: 150,
  },
  {
    id: 4,
    title: '1-4 只進不退',
    description: '這關的魔法場地受到限制，你無法「向上」或「向左」走！',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 2, gridY: 2, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 8, emoji: '🦇', label: '吸血蝙蝠' },
    obstacles: [
      { x: 4, y: 2, type: 'rock' },
      { x: 6, y: 4, type: 'rock' },
      { x: 8, y: 6, type: 'rock' },
      { x: 2, y: 8, type: 'rock' },
      { x: 3, y: 8, type: 'rock' },
      { x: 4, y: 8, type: 'rock' },
      { x: 5, y: 8, type: 'rock' }, 
      { x: 2, y: 7, type: 'rock' },
      { x: 3, y: 7, type: 'rock' },
      { x: 4, y: 7, type: 'rock' },
      { x: 5, y: 7, type: 'rock' }
    ],
    restrictions: { forbidden: ['moveUp', 'moveLeft'], maxBlocks: 12 },
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveDown', 'moveRight', 'attack'],
    failMessages: { outOfBounds: '🚫 走錯方向了！小心不要撞到石頭或邊界。' },
    hint: '既然只能向右和向下，遇到石頭時就必須提前轉彎走出階梯狀路線！',
    xpReward: 200,
  },
  {
    id: 5,
    title: '1-5 迷霧守衛 (Boss)',
    description: '第一章綜合測驗，最遙遠的距離與最多的障礙。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 8, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 1, emoji: '🛡️', label: '重甲守衛' },
    restrictions: { maxBlocks: 14 },
    obstacles: [
      { x: 2, y: 7, type: 'rock' },
      { x: 3, y: 6, type: 'rock' },
      { x: 4, y: 5, type: 'rock' },
      { x: 5, y: 4, type: 'rock' },
      { x: 1, y: 1, type: 'rock' },
      { x: 8, y: 8, type: 'rock' },
    ],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveLeft', 'moveRight', 'attack'],
    failMessages: { maxStepsExceeded: '👣 步數耗盡！請重新檢視路線是否繞了遠路。' },
    hint: '這需要寫很多行程式碼，保持耐心，仔細核對每一步！',
    xpReward: 300,
  },

  // ================= 第二章：規律步道 (強制迴圈 + 🌟積木精準限制) =================
  {
    id: 6,
    title: '2-1 節能法師',
    description: '這條路很長，用最少的積木走完它。',
    // 🌟 新增：迴圈教學
    tutorial: {
      message: '【新指令解鎖】，這條路太長了，單步移動會超過能量限制！我來傳授你「for」迴圈：<br><br><div class="bg-[#0a0e27] border border-[#333355] text-[#00d4aa] font-mono px-3 py-2 rounded-lg text-sm text-left shadow-inner tracking-wider">for(3, () => {<br>&nbsp;&nbsp;moveRight();<br>});</div><br>像這樣，就會自動重複執行三次向右移動！',
      newCommand: 'for'
    },
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 4, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 4, emoji: '👾', label: '迴圈怪' },
    restrictions: { maxBlocks: 4 },
    requiredCommand: ['for_loop'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveRight', 'attack', 'for'],
    failMessages: {
      missingCommand: '❌ 你必須使用「for 迴圈」才能過關！',
      tooManyBlocks: '🧱 積木用太多了！請把重複的動作放進迴圈裡。'
    },
    hint: '如果只用單步移動，積木數量會超過限制喔！請使用「迴圈」。',
    xpReward: 350,
  },
  {
    id: 7,
    title: '2-2 階梯法陣',
    description: '迴圈不只能裝一個動作，試著放入組合技。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 1, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 7, gridY: 6, emoji: '🐍', label: '劇毒蛇' },
    obstacles: [
      { x: 2, y: 1, type: 'rock' },
      { x: 3, y: 2, type: 'rock' },
      { x: 4, y: 3, type: 'rock' }
    ],
    restrictions: { maxBlocks: 5 }, 
    requiredCommand: ['for_loop'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveRight', 'moveDown', 'attack', 'for'],
    hint: '觀察規律：每次都是「向下 1 步，向右 1 步」，把這兩個動作都放進 for 中！',
    xpReward: 400,
  },
  {
    id: 8,
    title: '2-3 雙重衝刺',
    description: '串接多個迴圈來轉彎。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 2, gridY: 2, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 7, emoji: '🐺', label: '荒野狼' },
    restrictions: { maxBlocks: 7 }, 
    requiredCommand: ['for_loop'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveRight', 'moveDown', 'attack', 'for'],
    hint: '先用一個迴圈走到最右邊，再用另一個迴圈走到最下面。',
    xpReward: 450,
  },
  {
    id: 9,
    title: '2-4 碎石迷陣',
    description: '在障礙物中尋找重複的路徑。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 0, gridY: 2, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 7, gridY: 5, emoji: '🕷️', label: '巨型蜘蛛' },
    obstacles: [
      { x: 3, y: 2, type: 'rock' },
      { x: 5, y: 3, type: 'rock' },
      { x: 7, y: 4, type: 'rock' }
    ],
    restrictions: { maxBlocks: 6 }, 
    requiredCommand: ['for_loop'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'attack', 'for'],
    hint: '迴圈可以包裝重複的閃避動作。',
    xpReward: 500,
  },
  {
    id: 10,
    title: '2-5 規律極限 (Boss)',
    description: '第二章綜合測驗，極限積木挑戰。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 8, gridY: 8, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 1, gridY: 0, emoji: '👑', label: 'Bug國王' },
    obstacles: [
      { x: 8, y: 7, type: 'rock' },
      { x: 7, y: 6, type: 'rock' },
      { x: 6, y: 5, type: 'rock' },
      { x: 5, y: 4, type: 'rock' },
      { x: 4, y: 3, type: 'rock' },
      { x: 3, y: 2, type: 'rock' },
      { x: 2, y: 1, type: 'rock' }
    ],
    restrictions: { maxBlocks: 5 }, 
    requiredCommand: ['for_loop'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveLeft', 'attack', 'for'],
    hint: '仔細計算自己到怪物需要重複幾次左移與上移的組合。',
    xpReward: 600,
  },

  // ================= 第三章：陷阱地底 (單純條件過渡 -> 複合條件) =================
  {
    id: 11,
    title: '3-1 盲目探索 (基礎判斷)',
    description: '前方有牆壁！使用感應器來越過這堵牆。',
    // 🌟 新增：If 教學
    tutorial: {
      message: '地底佈滿未知障礙，你需要學會讓程式自己做判斷！使用「if (如果)」搭配雷達：<br><br><div class="bg-[#0a0e27] border border-[#333355] text-[#00d4aa] font-mono px-3 py-2 rounded-lg text-sm text-left shadow-inner tracking-wider">if (isWall()) {<br>&nbsp;&nbsp;moveUp();<br>}</div><br>像這樣，當雷達偵測到前方有牆壁時，法師就會自動往上走來閃避喔！',
      newCommand: 'if'
    },
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 2, gridY: 5, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 6, gridY: 5, emoji: '🔥', label: '火元素' },
    obstacles: [{ x: 4, y: 5, type: 'rock' }],
    restrictions: { maxBlocks: 10 }, 
    requiredCommand: ['if_else', 'isWall'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'attack', 'if', 'isWall'],
    hint: '先用 if 檢查。如果前方有牆，就往上走避開它。',
    xpReward: 700,
  },
  {
    id: 12,
    title: '3-2 岔路抉擇 (If-Else)',
    description: '有障礙就繞路，沒障礙就直走。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 2, gridY: 4, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 7, gridY: 4, emoji: '🗿', label: '巨石怪' },
    obstacles: [{ x: 5, y: 4, type: 'wall' }],
    restrictions: { maxBlocks: 14 }, 
    requiredCommand: ['if_else', 'isWall'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'attack', 'if', 'else', 'isWall'],
    hint: 'if (前方有障礙) { 繞路 } else { 前進 }',
    xpReward: 750,
  },
  {
    id: 13,
    title: '3-3 巡邏警戒 (迴圈 + 判斷)',
    description: '邊走邊掃描，把雷達裝進迴圈裡。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 5, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 5, emoji: '🧟', label: '殭屍Bug' },
    obstacles: [{ x: 3, y: 5, type: 'rock' }, { x: 6, y: 5, type: 'rock' }],
    restrictions: { maxBlocks: 11 }, 
    requiredCommand: ['for_loop', 'if_else', 'isWall'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'attack', 'for', 'if', 'else', 'isWall'],
    hint: '利用for迴圈 { 如果有障礙 -> 繞路，否則 -> 前進 }',
    xpReward: 800,
  },
  {
    id: 14,
    title: '3-4 終極雷達',
    description: '面對未知的多重障礙。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 0, gridY: 9, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 0, emoji: '🌵', label: '變異植物' },
    obstacles: [{ x: 9, y: 1, type: 'rock' }, { x: 9, y: 2, type: 'rock' }, 
                { x: 2, y: 9, type: 'rock' }, { x: 2, y: 8, type: 'rock' },
                { x: 8, y: 2, type: 'rock' }, { x: 8, y: 3, type: 'rock' },
                { x: 7, y: 4, type: 'rock' },
                { x: 4, y: 6, type: 'rock' }, { x: 4, y: 7, type: 'rock' },
                { x: 5, y: 5, type: 'rock' } ,{ x: 5, y: 6, type: 'rock' }],
    restrictions: { maxBlocks: 10 },
    requiredCommand: ['for_loop', 'if_else', 'isWall'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'attack', 'for', 'if', 'else', 'isWall'],
    hint: '你的迴圈必須完美處理「遇到障礙」和「暢通無阻」兩種情況。',
    xpReward: 900,
  },
  {
    id: 15,
    title: '3-5 陷阱領主 (Boss)',
    description: '第三章綜合測驗，隨時會踩到陷阱。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 5, gridY: 8, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 5, gridY: 0, emoji: '🐉', label: '混沌毒龍' },
    obstacles: [{ x: 5, y: 6, type: 'lava' }, { x: 4, y: 4, type: 'lava' }, { x: 5, y: 2, type: 'lava' }],
    restrictions: { maxBlocks: 11 },
    requiredCommand: ['for_loop', 'if_else', 'isWall'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveLeft', 'moveRight', 'attack', 'for', 'if', 'else', 'isWall'],
    hint: '這關的重點是「每一步都要小心」，你的程式必須在迴圈裡完美處理每個位置的狀況！', 
    xpReward: 1000,
  },

  // ================= 第四章：萬物自動 (先拆解 Function 與 While，再合併) =================
  {
    id: 16,
    title: '4-1 無盡追尋 (While迴圈)',
    description: '地圖被迷霧壟罩，走到碰面為止。',
    // 🌟 新增：While 教學
    tutorial: {
      message: '在這片無盡的迷霧中，我們不知道敵人有多遠。使用「while (當)」迴圈：<br><br><div class="bg-[#0a0e27] border border-[#333355] text-[#00d4aa] font-mono px-3 py-2 rounded-lg text-sm text-left shadow-inner tracking-wider">while (!isEnemy()) {<br>&nbsp;&nbsp;moveRight();<br>}</div><br>注意前面的驚嘆號 <code>!</code> 代表「相反」。這段咒語的意思是：當「還沒遇到」敵人時，法師就會不斷自動向右前進！',
      newCommand: 'while'
    },
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 3, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 3, emoji: '🎯', label: '標靶怪' },
    restrictions: { hideDistance: true, maxExecutionLoops: 50, maxBlocks: 4 }, 
    requiredCommand: ['while_loop', 'isEnemy'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveRight', 'attack', 'while', 'isEnemy'],
    hint: 'while (!isEnemy()) { 向右走; }',
    xpReward: 1200,
  },
  {
    id: 17,
    title: '4-2 記憶法術 (Function 基礎)',
    description: '閃避的動作太繁瑣了？把它打包成自訂指令！',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 2, gridY: 1, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 8, emoji: '👹', label: '雙角惡魔' },
    obstacles: [{ x: 3, y: 3, type: 'rock' }, { x: 5, y: 5, type: 'rock' }, { x: 7, y: 7, type: 'rock' }],
    restrictions: { maxBlocks: 8 }, 
    requiredCommand: ['function'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveDown', 'moveRight', 'attack', 'function', 'for'],
    hint: '先定義 function dodge() { 下; 右; }，主程式裡就可以呼叫 dodge() 了！',
    xpReward: 1500,
  },
  {
    id: 18,
    title: '4-3 智慧導航 (While + If)',
    description: '結合自動前進與自動避障。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 7, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 7, emoji: '🦅', label: '疾風巨鷹' },
    obstacles: [{ x: 4, y: 7, type: 'rock' }],
    restrictions: { maxExecutionLoops: 50, maxBlocks: 12 }, 
    requiredCommand: ['while_loop', 'if_else', 'isEnemy', 'isWall'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'attack', 'while', 'if', 'else', 'isEnemy', 'isWall'],
    hint: 'while (!isEnemy()) { 如果前方有牆就繞路，否則前進 }',
    xpReward: 1800,
  },
  {
    id: 19,
    title: '4-4 模組大軍 (While + Function)',
    description: '多重函式與主程式的協作。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 8, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 9, gridY: 1, emoji: '🌋', label: '熔岩巨獸' },
    obstacles: [{ x: 2, y: 6, type: 'rock' }, { x: 4, y: 5, type: 'rock' }, { x: 6, y: 3, type: 'rock' }],
    restrictions: { maxExecutionLoops: 80, maxBlocks: 12 },
    requiredCommand: ['while_loop', 'function', 'isEnemy', 'isWall'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveRight', 'attack', 'while', 'if', 'else', 'function', 'isEnemy', 'isWall'],
    hint: '把「閃避或斜走」寫成獨立的 function，這就是架構師的思維。',
    xpReward: 2000,
  },
 {
    id: 20,
    title: '4-5 傳奇自動化 (Final Boss)',
    description: '寫出一個能適應任何地形並自動過關的終極 AI。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 4, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 4, emoji: '👑', label: '深淵史萊姆魔王' },
    obstacles: [
      { x: 3, y: 4, type: 'rock' }, { x: 3, y: 5, type: 'rock' }, 
      { x: 6, y: 4, type: 'rock' }, { x: 6, y: 5, type: 'rock' }
    ],
    restrictions: { hideDistance: true, maxBlocks: 14, maxExecutionLoops: 100 },
    requiredCommand: ['while_loop', 'if_else', 'function', 'isEnemy', 'isWall'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'moveLeft', 'attack', 'while', 'if', 'else', 'function', 'isEnemy', 'isWall'],
    hint: '先定義好閃避的 function 工具，然後用一個乾淨的 while 迴圈迎戰吧！',
    xpReward: 3000,
    successMessage: '🏆 傳奇誕生！你已經完全掌握了程式邏輯，成為魔法程式之神！',
  },
  // ================= 🌟 第五章：遠程奧義 (遠程射擊與彈道規劃) =================
  {
    id: 21,
    title: '5-1 奧術飛彈',
    description: '解鎖遠程攻擊 shoot(X, Y)！請站在原地施展遠程攻擊將怪物狙擊！',
    // 🌟 修改：Shoot(1,0) 直線遠程教學
    tutorial: {
      message: '前方敵人太遠了，走過去會有危險！我來傳授你遠程奧義：<code class="bg-[#0a0e27] border border-[#ffbb33]/30 text-[#ffbb33] font-mono px-1.5 py-0.5 rounded text-sm mx-1">shoot(X, Y)</code><br><br><div class="bg-[#0a0e27] border border-[#333355] text-[#00d4aa] font-mono px-3 py-2 rounded-lg text-sm text-left shadow-inner tracking-wider">shoot(1, 0);</div><br><b>X</b> 代表水平方向（1 向右，-1 向左），<b>Y</b> 代表垂直方向（0 代表不上下偏）。這行咒語會發射一枚向右直飛的飛彈，試著狙擊蝙蝠吧！',
      newCommand: 'shoot'
    },
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 2, gridY: 5, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 7, gridY: 5, emoji: '🦇', label: '遠程吸血蝠' },
    obstacles: [],
    restrictions: { maxBlocks: 1 }, 
    requiredCommand: ['shoot'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['shoot'], 
    failMessages: {
      missingCommand: '❌ 這關不能走過去！你必須使用「shoot」積木在遠處狙擊目標！'
    },
    hint: '開火路線完全敞通！直接在程式中填入一個 shoot(1, 0) 積木，飛彈就會直線攻擊怪物！',
    xpReward: 3200,
    successMessage: '🏹 轟！遠程魔法威力強大，你甚至不需要挪動腳步！'
  },
  {
    id: 22,
    title: '5-2 調整彈道',
    description: '利用 shoot(X, Y) 的彈道特性，調整位置讓飛彈能夠擊中敵人！',
    // 🌟 修改：Shoot(1,1) 斜角彈道教學
    tutorial: {
      message: '敵人躲在斜對角！普通的直線魔法打不到牠，我們需要調整彈道。<br><br><div class="bg-[#0a0e27] border border-[#333355] text-[#00d4aa] font-mono px-3 py-2 rounded-lg text-sm text-left shadow-inner tracking-wider">shoot(1, 1);</div><br>將 <b>X</b> 設為 1 (向右)，<b>Y</b> 設為 1 (向下)，飛彈就會往「右下方」斜向狙擊！',
      newCommand: 'shoot'
    },
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 2, gridY: 2, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 7, gridY: 7, emoji: '👹', label: '躲藏的小鬼' },
    obstacles: [],
    restrictions: { maxBlocks: 1 },
    requiredCommand: ['shoot'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['shoot'],
    failMessages: {
      hitObstacle: '💥 飛彈在半路撞上高牆爆炸了！看來必須移動到跟怪物同一列（row 6）才能打中牠。'
    },
    hint: '利用 shoot 朝指定的方向發射，X軸為水平（方向右為正，方向左為負），Y軸為垂直（方向下為正，方向上為負）。',
    xpReward: 3500,
    successMessage: '🎯 聰明的決策！完美的斜角狙擊視線！'
  },
  {
    id: 23,
    title: '5-3 火力壓制 (迴圈狙擊)',
    description: '射程受到極度限制！利用 for 迴圈編寫出「更遠的射程」精準打擊目標。',
    // 🌟 修改：Function + Loop + Shoot 移動射擊教學
    tutorial: {
      message: '這關的怪物移動路徑特殊！我們要把移動動作打包成一個叫 <code>arror</code> 的函式，並傳給 <code>shoot()</code> 執行：<br><br><div class="bg-[#0a0e27] border border-[#333355] text-[#00d4aa] font-mono px-3 py-2 rounded-lg text-sm text-left shadow-inner tracking-wider">function arror(p) {<br>&nbsp;&nbsp;for(3, () => {<br>&nbsp;&nbsp;&nbsp;&nbsp;p.moveRight();<br>&nbsp;&nbsp;});<br>}<br><br>shoot(arror);</div><br>這裡的 <code>p</code> 代表「子彈」，這段代碼會自動讓子彈執行三次右移，然後進行精準狙擊！',
      newCommand: 'function'
    },
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 0, gridY: 4, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 9, gridY: 4, emoji: '💎', label: '遠古結晶怪' },
    restrictions: { maxBlocks: 6 },
    requiredCommand: ['for_loop', 'shoot', 'function'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveRight', 'shoot', 'for', 'function'],
    failMessages: {
      tooManyBlocks: '🧱 積木數量超標了！請善用 for 迴圈來包裝重複的「向右」和「射擊」動作。'
    },
    hint: '利用 function 加上 for 迴圈的組合，邊走邊開火，讓飛彈一路追蹤到敵人！',
    xpReward: 4000,
    successMessage: '🔁 太流暢了！這就是迴圈配上射擊的移動重火力壓制！'
  },
  {
    id: 24,
    title: '5-4 盲區雷達獵手',
    description: '走廊上可能隨機布滿高牆！結合 if-else 與 isWall 雷達，有障礙就繞路，開闊處就開火！',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 5, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 5, emoji: '🦂', label: '迷宮巨蠍' },
    obstacles: [
      { x: 4, y: 5, type: 'rock' } 
    ],
    restrictions: { maxBlocks: 12 },
    requiredCommand: ['for_loop', 'if_else', 'isWall', 'shoot', 'function'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'shoot', 'for', 'if', 'else', 'isWall','function'],
    hint: '射程範圍內有障礙物，利用 if-else 來處理迴避障礙物，讓飛彈變成自動導航攻擊目標！',
    xpReward: 4500,
    successMessage: '🧠 完美運作！你的雷達能夠在沒有威脅時立刻實施精準打擊！'
  },
  {
    id: 25,
    title: '5-5 終焉狙擊狂潮 (Final Boss)',
    description: '終極自動化考核！編寫一段能夠無限掃描戰場、靈活走位避開高牆，直到用神速射擊摧毀魔王的終極代碼。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 2, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 6, emoji: '🔱', label: '深淵滅世者' },
    obstacles: [
      { x: 3, y: 2, type: 'rock' }, { x: 3, y: 3, type: 'rock' },
      { x: 7, y: 4, type: 'rock' }, { x: 7, y: 5, type: 'rock' },
    ],
    restrictions: { maxExecutionLoops: 120, maxBlocks: 14 },
    requiredCommand: ['while_loop', 'if_else', 'isWall', 'shoot', 'function'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'shoot', 'while', 'if', 'else', 'isWall', 'isEnemy', 'function'],
    hint: '寫一個 while 迴圈，讓子彈變成自動導航的智能飛彈，能夠在戰場上靈活閃避障礙並持續追蹤目標直到擊中！',
    xpReward: 6000,
    successMessage: '🏆 【傳奇狙擊之神】誕生！你寫出的程式代碼已經具備高等 AI 的自動狙擊規劃邏輯，完美通關！'
  }
];