export const levels = [
  // ================= 第一章：迷霧森林 (精準的步數控制與方向感) =================
  {
    id: 1,
    title: '1-1 窄門試煉',
    description: '學習最基本的移動，並繞過前方的障礙物。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 2, gridY: 5, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 6, gridY: 5, emoji: '👾', label: '弱小Bug' },
    obstacles: [{ x: 4, y: 5, type: 'rock' }],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveLeft', 'moveRight', 'attack'],
    restrictions: { maxSteps: 7 }, // 修正步數，確保能繞過石頭
    failMessages: {
      hitObstacle: '💥 哎呀！撞到石頭了，請先往上或往下繞開它。',
      maxStepsExceeded: '👣 走太多步囉！請找出最直接的路線。'
    },
    hint: '前方有石頭！試著先「向上」走一步來繞過它。',
    xpReward: 100,
    successMessage: '✨ 好的開始！你成功繞過了第一個障礙！',
  },
  {
    id: 2,
    title: '1-2 高牆阻擋',
    description: '面對更長的牆壁，你需要規劃更遠的路線。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 2, gridY: 2, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 6, gridY: 2, emoji: '👹', label: '紅眼怪物' },
    obstacles: [
      { x: 4, y: 1, type: 'wall' },
      { x: 4, y: 2, type: 'wall' },
      { x: 4, y: 3, type: 'wall' }
    ],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveLeft', 'moveRight', 'attack'],
    restrictions: { maxSteps: 10 },
    failMessages: { hitObstacle: '💥 牆壁太高了跨不過去，必須從下面繞！' },
    hint: '這道牆很長，你需要先往下走好幾步才能繞過去。',
    xpReward: 120,
    successMessage: '✨ 路線清晰！再長的牆也擋不住你。',
  },
  {
    id: 3,
    title: '1-3 Ｚ字迷陣',
    description: '在錯綜複雜的岩石中穿梭。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 1, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 6, gridY: 6, emoji: '👻', label: '幽靈Bug' },
    obstacles: [
      { x: 3, y: 1, type: 'rock' }, { x: 3, y: 2, type: 'rock' },
      { x: 4, y: 5, type: 'rock' }, { x: 4, y: 6, type: 'rock' }
    ],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveLeft', 'moveRight', 'attack'],
    restrictions: { maxSteps: 10 },
    failMessages: { maxStepsExceeded: '👣 步數耗盡！你沒有走在最短的 Z 字路線上。' },
    hint: '仔細觀察空隙，你的步數只夠你走最完美的路線。',
    xpReward: 150,
  },
  {
    // 🌟 重新設計：1-4 只進不退 (無法穿牆，透過限制方向製造挑戰)
    id: 4,
    title: '1-4 只進不退',
    description: '這關的魔法場地受到限制，你無法「向上」或「向左」走！',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 2, gridY: 2, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 8, emoji: '🦇', label: '吸血蝙蝠' },
    obstacles: [
      { x: 4, y: 2, type: 'rock' },
      { x: 6, y: 4, type: 'rock' },
      { x: 8, y: 6, type: 'rock' }
    ],
    restrictions: { forbidden: ['moveUp', 'moveLeft'], maxSteps: 12 },
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveDown', 'moveRight', 'attack'],
    failMessages: { outOfBounds: '🚫 走錯方向了！小心不要撞到石頭或邊界。' },
    hint: '既然只能向右和向下，遇到石頭時就必須提前轉彎走出階梯狀路線！',
    xpReward: 200,
  },
  {
    id: 5,
    title: '1-5 迷霧守衛 (Boss)',
    description: '第一章綜合測驗，最遙遠的距離與最多的障礙。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 8, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 1, emoji: '🛡️', label: '重甲守衛' },
    obstacles: [
      { x: 2, y: 7, type: 'rock' },
      { x: 3, y: 6, type: 'rock' },
      { x: 4, y: 5, type: 'rock' },
      { x: 5, y: 4, type: 'rock' }
    ],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveLeft', 'moveRight', 'attack'],
    restrictions: { maxSteps: 14 },
    failMessages: { maxStepsExceeded: '👣 步數耗盡！請重新檢視路線是否繞了遠路。' },
    hint: '這需要寫很多行程式碼，保持耐心，仔細核對每一步！',
    xpReward: 300,
  },

  // ================= 第二章：規律步道 (強制迴圈 + 🌟積木精準限制) =================
  {
    id: 6,
    title: '2-1 節能法師',
    description: '這條路很長，用最少的積木走完它。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 4, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 4, emoji: '👾', label: '迴圈怪' },
    restrictions: { maxBlocks: 4 }, // for(2) + right(1) + attack(1) = 4
    requiredCommand: ['for_loop'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveRight', 'attack', 'for'],
    failMessages: {
      missingCommand: '❌ 你必須使用「for 迴圈」才能過關！',
      tooManyBlocks: '🧱 積木用太多了！請把重複的動作放進迴圈裡。'
    },
    hint: '如果只用單步移動，積木數量會超過限制喔！請使用「迴圈」。',
    xpReward: 350,
  },
  {
    id: 7,
    title: '2-2 階梯法陣',
    description: '迴圈不只能裝一個動作，試著放入組合技。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 1, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 7, gridY: 6, emoji: '🐍', label: '劇毒蛇' },
    obstacles: [
      { x: 2, y: 1, type: 'rock' },
      { x: 3, y: 2, type: 'rock' },
      { x: 4, y: 3, type: 'rock' }
    ],
    restrictions: { maxBlocks: 5 }, // for(2) + down(1) + right(1) + attack(1) = 5
    requiredCommand: ['for_loop'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveRight', 'moveDown', 'attack', 'for'],
    hint: '觀察規律：每次都是「向下 1 步，向右 1 步」，把這兩個動作都放進 for 中！',
    xpReward: 400,
  },
  {
    id: 8,
    title: '2-3 雙重衝刺',
    description: '串接多個迴圈來轉彎。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 2, gridY: 2, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 7, emoji: '🐺', label: '荒野狼' },
    restrictions: { maxBlocks: 7 }, // for(2) + right(1) + for(2) + down(1) + attack(1) = 7
    requiredCommand: ['for_loop'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveRight', 'moveDown', 'attack', 'for'],
    hint: '先用一個迴圈走到最右邊，再用另一個迴圈走到最下面。',
    xpReward: 450,
  },
  {
    id: 9,
    title: '2-4 碎石迷陣',
    description: '在障礙物中尋找重複的路徑。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 0, gridY: 2, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 7, gridY: 5, emoji: '🕷️', label: '巨型蜘蛛' },
    obstacles: [
      { x: 3, y: 2, type: 'rock' },
      { x: 5, y: 3, type: 'rock' },
      { x: 7, y: 4, type: 'rock' }
    ],
    restrictions: { maxBlocks: 6 }, // for(2) + right(2) + down(1) + attack(1) = 6
    requiredCommand: ['for_loop'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'attack', 'for'],
    hint: '迴圈可以包裝重複的閃避動作。',
    xpReward: 500,
  },
  {
    id: 10,
    title: '2-5 規律極限 (Boss)',
    description: '第二章綜合測驗，極限積木挑戰。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 8, gridY: 8, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 1, gridY: 0, emoji: '👑', label: 'Bug國王' },
    obstacles: [
      { x: 8, y: 7, type: 'rock' },
      { x: 7, y: 6, type: 'rock' },
      { x: 6, y: 5, type: 'rock' },
      { x: 5, y: 4, type: 'rock' },
      { x: 4, y: 3, type: 'rock' },
      { x: 3, y: 2, type: 'rock' },
      { x: 2, y: 1, type: 'rock' }
    ],
    restrictions: { maxBlocks: 5 }, // for(2) + left(1) + up(1) + attack(1) = 5
    requiredCommand: ['for_loop'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveLeft', 'attack', 'for'],
    hint: '仔細計算從 (8,8) 到 (1,1) 需要重複幾次左移與上移的組合。',
    xpReward: 600,
  },

  // ================= 第三章：陷阱地底 (單純條件過渡 -> 複合條件) =================
  {
    id: 11,
    title: '3-1 盲目探索 (基礎判斷)',
    description: '前方【可能】有岩漿！使用感應器來保護自己。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 2, gridY: 5, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 6, gridY: 5, emoji: '🔥', label: '火元素' },
    obstacles: [{ x: 4, y: 5, type: 'lava' }],
    restrictions: { maxBlocks: 10 }, // moveRight(2) + if(1) + isWall(1) + up(1) + right(2) + down(1) + attack(1) = 9
    requiredCommand: ['if_else', 'isWall'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'attack', 'if', 'isWall'],
    hint: '先用 if 檢查。如果前方有牆，就往上走避開它。',
    xpReward: 700,
  },
  {
    id: 12,
    title: '3-2 岔路抉擇 (If-Else)',
    description: '有障礙就繞路，沒障礙就直走。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 2, gridY: 4, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 7, gridY: 4, emoji: '🗿', label: '巨石怪' },
    obstacles: [{ x: 5, y: 4, type: 'wall' }],
    restrictions: { maxBlocks: 14 }, // if/else/isWall 算進去約 13 個積木
    requiredCommand: ['if_else', 'isWall'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'attack', 'if', 'else', 'isWall'],
    hint: 'if (前方有障礙) { 繞路 } else { 前進 }',
    xpReward: 750,
  },
  {
    id: 13,
    title: '3-3 巡邏警戒 (迴圈 + 判斷)',
    description: '邊走邊掃描，把雷達裝進迴圈裡。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 5, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 5, emoji: '🧟', label: '殭屍Bug' },
    obstacles: [{ x: 3, y: 5, type: 'rock' }, { x: 6, y: 5, type: 'rock' }],
    restrictions: { maxBlocks: 11 }, // for(2) + if(1) + isWall(1) + else(1) + 繞路(3) + 直走(1) + attack(1) = 10
    requiredCommand: ['for_loop', 'if_else', 'isWall'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'attack', 'for', 'if', 'else', 'isWall'],
    hint: '重複執行 7 次：{ 如果有障礙 -> 繞路，否則 -> 前進 }',
    xpReward: 800,
  },
  {
    id: 14,
    title: '3-4 終極雷達',
    description: '面對未知的多重障礙。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 0, gridY: 9, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 0, emoji: '🌵', label: '變異植物' },
    obstacles: [{ x: 9, y: 1, type: 'rock' }, { x: 9, y: 2, type: 'rock' }, 
                { x: 2, y: 9, type: 'rock' }, { x: 2, y: 8, type: 'rock' },
                { x: 8, y: 2, type: 'rock' }, { x: 8, y: 3, type: 'rock' },
                { x: 7, y: 4, type: 'rock' },
                { x: 4, y: 6, type: 'rock' }, { x: 4, y: 7, type: 'rock' },
                { x: 5, y: 5, type: 'rock' } ,{ x: 5, y: 6, type: 'rock' }],
    restrictions: { maxBlocks: 10 },
    requiredCommand: ['for_loop', 'if_else', 'isWall'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'attack', 'for', 'if', 'else', 'isWall'],
    hint: '你的迴圈必須完美處理「遇到障礙」和「暢通無阻」兩種情況。',
    xpReward: 900,
  },
  {
    id: 15,
    title: '3-5 陷阱領主 (Boss)',
    description: '第三章綜合測驗，隨時會踩到陷阱。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 5, gridY: 8, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 5, gridY: 0, emoji: '🐉', label: '混沌毒龍' },
    obstacles: [{ x: 5, y: 6, type: 'lava' }, { x: 4, y: 4, type: 'lava' }, { x: 5, y: 2, type: 'lava' }],
    restrictions: { maxBlocks: 11 },
    requiredCommand: ['for_loop', 'if_else', 'isWall'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveLeft', 'moveRight', 'attack', 'for', 'if', 'else', 'isWall'],
    xpReward: 1000,
  },

  // ================= 第四章：萬物自動 (先拆解 Function 與 While，再合併) =================
  {
    id: 16,
    title: '4-1 無盡追尋 (While迴圈)',
    description: '地圖被迷霧壟罩，走到碰面為止。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 3, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 3, emoji: '🎯', label: '標靶怪' },
    restrictions: { hideDistance: true, maxExecutionLoops: 50, maxBlocks: 4 }, // while(1) + isEnemy(1) + right(1) + attack(1) = 4
    requiredCommand: ['while_loop', 'isEnemy'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveRight', 'attack', 'while', 'isEnemy'],
    hint: 'while (!isEnemy()) { 向右走; }',
    xpReward: 1200,
  },
  {
    id: 17,
    title: '4-2 記憶法術 (Function 基礎)',
    description: '閃避的動作太繁瑣了？把它打包成自訂指令！',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 2, gridY: 1, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 8, emoji: '👹', label: '雙角惡魔' },
    obstacles: [{ x: 3, y: 3, type: 'rock' }, { x: 5, y: 5, type: 'rock' }, { x: 7, y: 7, type: 'rock' }],
    restrictions: { maxBlocks: 8 }, // function(1)+dodge內(2) + for(2)+呼叫(1) + attack(1) = 7
    requiredCommand: ['function'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveDown', 'moveRight', 'attack', 'function', 'for'],
    hint: '先定義 function dodge() { 下; 右; }，主程式裡就可以呼叫 dodge() 了！',
    xpReward: 1500,
  },
  {
    id: 18,
    title: '4-3 智慧導航 (While + If)',
    description: '結合自動前進與自動避障。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 7, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 7, emoji: '🦅', label: '疾風巨鷹' },
    obstacles: [{ x: 4, y: 7, type: 'rock' }],
    restrictions: { maxExecutionLoops: 50, maxBlocks: 12 }, 
    requiredCommand: ['while_loop', 'if_else', 'isEnemy', 'isWall'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'attack', 'while', 'if', 'else', 'isEnemy', 'isWall'],
    hint: 'while (!isEnemy()) { 如果前方有牆就繞路，否則前進 }',
    xpReward: 1800,
  },
  {
    id: 19,
    title: '4-4 模組大軍 (While + Function)',
    description: '多重函式與主程式的協作。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 8, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 9, gridY: 1, emoji: '🌋', label: '熔岩巨獸' },
    obstacles: [{ x: 2, y: 6, type: 'rock' }, { x: 4, y: 5, type: 'rock' }, { x: 6, y: 3, type: 'rock' }],
    restrictions: { maxExecutionLoops: 80, maxBlocks: 12 },
    requiredCommand: ['while_loop', 'function', 'isEnemy', 'isWall'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveRight', 'attack', 'while', 'if', 'else', 'function', 'isEnemy', 'isWall'],
    hint: '把「閃避或斜走」寫成獨立的 function，這就是架構師的思維。',
    xpReward: 2000,
  },
 {
    id: 20,
    title: '4-5 傳奇自動化 (Final Boss)',
    description: '寫出一個能適應任何地形並自動過關的終極 AI。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 4, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 4, emoji: '👑', label: '深淵史萊姆魔王' },
    obstacles: [
      { x: 3, y: 4, type: 'rock' }, { x: 3, y: 5, type: 'rock' }, 
      { x: 6, y: 4, type: 'rock' }, { x: 6, y: 5, type: 'rock' }
    ],
    restrictions: { hideDistance: true, maxBlocks: 14, maxExecutionLoops: 100 },
    requiredCommand: ['while_loop', 'if_else', 'function', 'isEnemy', 'isWall'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'moveLeft', 'attack', 'while', 'if', 'else', 'function', 'isEnemy', 'isWall'],
    hint: '先定義好閃避的 function 工具，然後用一個乾淨的 while 迴圈迎戰吧！',
    xpReward: 3000,
    successMessage: '🏆 傳奇誕生！你已經完全掌握了程式邏輯，成為魔法程式之神！',
  },
  // ================= 🌟 第五章：遠程奧義 (遠程射擊與彈道規劃) =================
  {
    id: 21,
    title: '5-1 奧術飛彈',
    description: '解鎖遠程攻擊 shoot(X, Y)！請站在原地施展 shoot(1,0) 將怪物狙擊！',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 2, gridY: 5, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 7, gridY: 5, emoji: '🦇', label: '遠程吸血蝠' },
    obstacles: [],
    restrictions: { maxBlocks: 1 }, // 只需要一塊 shoot 積木
    requiredCommand: ['shoot'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['shoot'], // 這關封印移動，強制學習遠程
    failMessages: {
      missingCommand: '❌ 這關不能走過去！你必須使用「shoot」積木在遠處狙擊目標！'
    },
    hint: '開火路線完全敞通！直接在程式中填入一個 「shoot」 積木，飛彈就會自動追蹤直線上的怪物！',
    xpReward: 3200,
    successMessage: '🏹 轟！遠程魔法威力強大，你甚至不需要挪動腳步！'
  },
  {
    id: 22,
    title: '5-2 調整彈道',
    description: '利用 shoot(X, Y) 的彈道特性，調整位置讓飛彈能夠擊中敵人！',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 2, gridY: 2, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 7, gridY: 7, emoji: '👹', label: '躲藏的小鬼' },
    obstacles: [],
    restrictions: { maxBlocks: 1 },
    requiredCommand: ['shoot'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['shoot'],
    failMessages: {
      hitObstacle: '💥 飛彈在半路撞上高牆爆炸了！看來必須移動到跟怪物同一列（row 6）才能打中牠。'
    },
    hint: '怪物在第 6 列 (Y=6)，你現在在第 2 列 (Y=2)。先向下移動 4 步，開闊後再使用 shoot！',
    xpReward: 3500,
    successMessage: '🎯 聰明的決策！移動並拉出完美的狙擊視線！'
  },
  {
    id: 23,
    title: '5-3 火力壓制 (迴圈狙擊)',
    description: '積木能量受到極度限制！利用 for 迴圈編寫出「前進一格、開火一發」的精準組合。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 0, gridY: 4, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 9, gridY: 4, emoji: '💎', label: '遠古結晶怪' },
    restrictions: { maxBlocks: 6 },
    requiredCommand: ['for_loop', 'shoot', 'function'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveRight', 'shoot', 'for', 'function'],
    failMessages: {
      tooManyBlocks: '🧱 積木數量超標了！請善用 for 迴圈來包裝重複的「向右」和「射擊」動作。'
    },
    hint: 'ˋ預設彈道為5格，利用function+for迴圈的組合，增加狙擊射程，讓飛彈一路追蹤到敵人！',
    xpReward: 4000,
    successMessage: '🔁 太流暢了！這就是迴圈配上射擊的移動重火力壓制！'
  },
  {
    id: 24,
    title: '5-4 盲區雷達獵手',
    description: '走廊上可能隨機布滿高牆！結合 if-else 與 isWall 雷達，有障礙就繞路，開闊處就開火！',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 5, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 5, emoji: '🦂', label: '迷宮巨蠍' },
    obstacles: [
      { x: 4, y: 5, type: 'rock' } // 擋在走廊中間
    ],
    restrictions: { maxBlocks: 12 },
    requiredCommand: ['for_loop', 'if_else', 'isWall', 'shoot', 'function'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'shoot', 'for', 'if', 'else', 'isWall','function'],
    hint: '在 5 次的迴圈內：如果 isWall() 前方有石頭，就走 moveUp 繞開；否則（else）就向右並大膽 shoot()！',
    xpReward: 4500,
    successMessage: '🧠 完美運作！你的雷達能夠在沒有威脅時立刻實施精準打擊！'
  },
  {
    id: 25,
    title: '5-5 終焉狙擊狂潮 (Final Boss)',
    description: '終極自動化考核！編寫一段能夠無限掃描戰場、靈活走位避開高牆，直到用神速射擊摧毀魔王的終極代碼。',
    grid_size: { cols: 10, rows: 10 },
    player: { gridX: 1, gridY: 2, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 6, emoji: '🔱', label: '深淵滅世者' },
    obstacles: [
      { x: 3, y: 2, type: 'rock' }, { x: 3, y: 3, type: 'rock' },
      { x: 7, y: 4, type: 'rock' }, { x: 7, y: 5, type: 'rock' },
    ],
    restrictions: { maxExecutionLoops: 120, maxBlocks: 14 },
    requiredCommand: ['while_loop', 'if_else', 'isWall', 'shoot', 'function'],
    victoryCondition: ['kill_enemy'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'shoot', 'while', 'if', 'else', 'isWall', 'isEnemy', 'function'],
    hint: '寫一個 while 迴圈，如果前面是牆就往下或往右繞開；如果在開闊地形且偵測到路線與 Boss 平行，就給牠致命一擊！',
    xpReward: 6000,
    successMessage: '🏆 【傳奇狙擊之神】誕生！你寫出的程式代碼已經具備高等 AI 的自動狙擊規劃邏輯，完美通關！'
  }
];