// src/game/scenes/LevelConfig.js

export const levels = [
  // ================= 第一章：迷霧森林 (基礎順序 + 障礙) =================
  {
    id: 1,
    title: '1-1 窄門試煉',
    description: '學習最基本的移動，並繞過前方的障礙物。',
    player: { gridX: 2, gridY: 5, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 6, gridY: 5, emoji: '👾', label: '弱小Bug' },
    obstacles: [
      { x: 4, y: 5, type: 'rock' } // 擋在正中間的石頭
    ],
    goals: ['繞過石頭', '擊敗敵人'],
    availableCommands: ['moveUp', 'moveDown', 'moveLeft', 'moveRight', 'attack'],
    hint: '前方有石頭！試著先向上或向下走一步來繞過它。',
    xpReward: 100,
    successMessage: '✨ 好的開始！你成功繞過了第一個障礙！',
  },
  {
    id: 2,
    title: '1-2 高牆阻擋',
    description: '面對更長的牆壁，你需要規劃更遠的路線。',
    player: { gridX: 2, gridY: 2, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 6, gridY: 2, emoji: '👹', label: '紅眼怪物' },
    obstacles: [
      { x: 4, y: 1, type: 'wall' },
      { x: 4, y: 2, type: 'wall' },
      { x: 4, y: 3, type: 'wall' }
    ],
    goals: ['繞過高牆', '抵達目標發動攻擊'],
    availableCommands: ['moveUp', 'moveDown', 'moveLeft', 'moveRight', 'attack'],
    hint: '這道牆很長，你需要先往下走好幾步才能繞過去。',
    xpReward: 120,
    successMessage: '✨ 路線清晰！再長的牆也擋不住你。',
  },
  {
    id: 3,
    title: '1-3 Ｚ字迷陣',
    description: '在錯綜複雜的岩石中穿梭。',
    player: { gridX: 1, gridY: 1, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 6, gridY: 6, emoji: '👻', label: '幽靈Bug' },
    obstacles: [
      { x: 3, y: 1, type: 'rock' }, { x: 3, y: 2, type: 'rock' },
      { x: 4, y: 5, type: 'rock' }, { x: 4, y: 6, type: 'rock' }
    ],
    goals: ['走出 Z 字型的路線', '不要撞到岩石'],
    availableCommands: ['moveUp', 'moveDown', 'moveLeft', 'moveRight', 'attack'],
    hint: '仔細觀察空隙，一步一步把指令排好。',
    xpReward: 150,
  },
  {
    id: 4,
    title: '1-4 限制之域',
    description: '這關你被施加了詛咒，無法向右轉！',
    player: { gridX: 4, gridY: 4, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 6, gridY: 4, emoji: '🦇', label: '吸血蝙蝠' },
    obstacles: [{ x: 5, y: 4, type: 'wall' }],
    restrictions: { forbidden: ['moveRight'] }, // 限制：不能使用向右移動
    goals: ['在不能向右走的情況下抵達目標'],
    availableCommands: ['moveUp', 'moveDown', 'moveLeft', 'attack'], // 沒有 moveRight
    hint: '不能向右走？那就只能往上或往下繞一大圈了！',
    xpReward: 200,
    successMessage: '✨ 逆境求生！你克服了指令限制！',
  },
  {
    id: 5,
    title: '1-5 迷霧守衛 (Boss)',
    description: '第一章綜合測驗，最遙遠的距離與最多的障礙。',
    player: { gridX: 1, gridY: 8, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 1, emoji: '🛡️', label: '重甲守衛' },
    obstacles: [
      { x: 2, y: 7 }, { x: 3, y: 6 }, { x: 4, y: 5 }, { x: 5, y: 4 }
    ],
    goals: ['跨越對角線', '避開斜向的防禦陣型'],
    availableCommands: ['moveUp', 'moveDown', 'moveLeft', 'moveRight', 'attack'],
    hint: '這需要寫很多行程式碼，保持耐心，仔細核對每一步！',
    xpReward: 300,
  },

  // ================= 第二章：規律步道 (迴圈 + 數量限制) =================
  {
    id: 6,
    title: '2-1 節能法師',
    description: '用最少的積木走最長的路。',
    player: { gridX: 1, gridY: 4, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 4, emoji: '👾', label: '迴圈怪' },
    restrictions: { maxBlocks: 4 }, // 限制：最多只能用 4 個積木
    goals: ['使用 repeat() 迴圈', '積木使用量不超過 4 個'],
    availableCommands: ['moveRight', 'attack', 'repeat'],
    hint: '如果只用單步移動，積木數量會超過限制喔！請使用「迴圈」。',
    xpReward: 350,
    successMessage: '✨ 魔法升級！你的程式碼變得簡潔有力了！',
  },
  {
    id: 7,
    title: '2-2 階梯法陣',
    description: '在迴圈內放入多個動作。',
    player: { gridX: 1, gridY: 1, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 6, gridY: 6, emoji: '🐍', label: '劇毒蛇' },
    obstacles: [
      { x: 2, y: 1 }, { x: 3, y: 2 }, { x: 4, y: 3 }
    ],
    restrictions: { maxBlocks: 5 },
    goals: ['找出移動的規律', '將規律放入迴圈中'],
    availableCommands: ['moveRight', 'moveDown', 'attack', 'repeat'],
    hint: '觀察規律：每次都是「向下 1 步，向右 1 步」，把這組動作放進 repeat 中！',
    xpReward: 400,
  },
  {
    id: 8,
    title: '2-3 雙重衝刺',
    description: '串接多個迴圈來轉彎。',
    player: { gridX: 2, gridY: 2, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 7, emoji: '🐺', label: '荒野狼' },
    restrictions: { maxBlocks: 6 },
    goals: ['使用兩個連續的 repeat()'],
    availableCommands: ['moveRight', 'moveDown', 'attack', 'repeat'],
    hint: '先用一個迴圈走到最右邊，再用另一個迴圈走到最下面。',
    xpReward: 450,
  },
  {
    id: 9,
    title: '2-4 碎石迷陣',
    description: '在障礙物中尋找重複的路徑。',
    player: { gridX: 1, gridY: 2, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 7, gridY: 5, emoji: '🕷️', label: '巨型蜘蛛' },
    obstacles: [
      { x: 3, y: 2 }, { x: 5, y: 3 }, { x: 7, y: 4 }
    ],
    restrictions: { maxBlocks: 7 },
    goals: ['結合迴圈與單步移動'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'attack', 'repeat'],
    hint: '迴圈可以包裝重複的閃避動作。',
    xpReward: 500,
  },
  {
    id: 10,
    title: '2-5 規律極限 (Boss)',
    description: '第二章綜合測驗，極限積木挑戰。',
    player: { gridX: 8, gridY: 8, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 1, gridY: 1, emoji: '👑', label: 'Bug國王' },
    obstacles: [
      { x: 6, y: 6 }, { x: 4, y: 4 }, { x: 2, y: 2 }
    ],
    restrictions: { maxBlocks: 6 },
    goals: ['用極少的積木跨越整張地圖'],
    availableCommands: ['moveUp', 'moveLeft', 'attack', 'repeat'],
    hint: '仔細計算從 (8,8) 到 (1,1) 需要重複幾次左移與上移的組合。',
    xpReward: 600,
    successMessage: '🏆 迴圈魔法精通！你已經具備了優化程式碼長度的能力！',
  },

  // ================= 第三章：陷阱地底 (條件判斷 + 感知) =================
  {
    id: 11,
    title: '3-1 盲目探索',
    description: '前方可能有岩漿！使用感應器來判斷。',
    player: { gridX: 2, gridY: 5, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 7, gridY: 5, emoji: '🔥', label: '火元素' },
    obstacles: [{ x: 4, y: 5, type: 'lava' }], 
    goals: ['使用 if 判斷式', '偵測到障礙物時繞路'],
    // 新增 isObstacleAhead (前方是否有障礙物) 與 if
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'attack', 'if', 'isObstacleAhead'], 
    hint: 'if (isObstacleAhead()) { 往上走; 往右走; 往下走; } else { 往右走; }',
    xpReward: 700,
    successMessage: '✨ 智慧初開！你的程式碼現在有「眼睛」了！',
  },
  {
    id: 12,
    title: '3-2 岔路抉擇',
    description: 'if-else 分支邏輯。',
    player: { gridX: 2, gridY: 4, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 7, gridY: 4, emoji: '🗿', label: '巨石怪' },
    obstacles: [{ x: 5, y: 4, type: 'wall' }],
    goals: ['使用 if-else', '有障礙就繞路，沒障礙就前進'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'attack', 'if', 'else', 'isObstacleAhead'],
    hint: 'if (前方有障礙) { 繞路; } else { 前進; }',
    xpReward: 750,
  },
  {
    id: 13,
    title: '3-3 巡邏警戒',
    description: '把雷達裝在迴圈裡，邊走邊掃描。',
    player: { gridX: 1, gridY: 5, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 5, emoji: '🧟', label: '殭屍Bug' },
    obstacles: [{ x: 3, y: 5 }, { x: 6, y: 5 }],
    goals: ['在 repeat 迴圈中放入 if-else'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'attack', 'repeat', 'if', 'else', 'isObstacleAhead'],
    hint: '重複執行「掃描並行動」：repeat(7) { if-else邏輯... }',
    xpReward: 800,
  },
  {
    id: 14,
    title: '3-4 終極雷達',
    description: '面對未知的多重障礙。',
    player: { gridX: 1, gridY: 2, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 2, emoji: '🌵', label: '變異植物' },
    obstacles: [{ x: 2, y: 2 }, { x: 4, y: 2 }, { x: 6, y: 2 }], 
    goals: ['寫出能連續避障的迴圈程式'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'attack', 'repeat', 'if', 'else', 'isObstacleAhead'],
    hint: '你的迴圈必須完美處理「遇到障礙」和「暢通無阻」兩種情況。',
    xpReward: 900,
  },
  {
    id: 15,
    title: '3-5 陷阱領主 (Boss)',
    description: '第三章綜合測驗，隨時會踩到陷阱。',
    player: { gridX: 5, gridY: 8, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 5, gridY: 1, emoji: '🐉', label: '混沌毒龍' },
    obstacles: [{ x: 5, y: 6 }, { x: 4, y: 4 }, { x: 5, y: 2 }],
    restrictions: { maxBlocks: 10 },
    goals: ['綜合運用迴圈與判斷式', '在積木限制內擊敗魔王'],
    availableCommands: ['moveUp', 'moveLeft', 'moveRight', 'attack', 'repeat', 'if', 'else', 'isObstacleAhead'],
    xpReward: 1000,
    successMessage: '🏆 邏輯判斷大師！你已經能寫出應對各種狀況的健壯程式了！',
  },

  // ================= 第四章：萬物自動 (進階邏輯與自動化) =================
  {
    id: 16,
    title: '4-1 直到盡頭',
    description: '你看不見敵人的距離，只能依賴 while 迴圈。',
    player: { gridX: 1, gridY: 3, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 3, emoji: '🎯', label: '標靶怪' },
    restrictions: { hideDistance: true }, // 限制：隱藏網格線或距離提示
    goals: ['使用 while 迴圈', '不必知道準確距離也能抵達目標'],
    availableCommands: ['moveRight', 'attack', 'while', 'isEnemyNear'], // 新增 isEnemyNear
    hint: '不知道要走幾步？試試：while (!isEnemyNear()) { moveRight(); }',
    xpReward: 1200,
    successMessage: '✨ 動態適應！while 迴圈讓你不必再辛苦算格子！',
  },
  {
    id: 17,
    title: '4-2 智慧導航',
    description: '結合 while 與 if-else 的終極追蹤邏輯。',
    player: { gridX: 1, gridY: 7, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 7, emoji: '🦅', label: '疾風巨鷹' },
    obstacles: [{ x: 4, y: 7 }],
    goals: ['建立自動追蹤並避障的邏輯'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'attack', 'while', 'if', 'else', 'isEnemyNear', 'isObstacleAhead'],
    hint: 'while (!isEnemyNear()) { 如果前方有障礙就繞路，否則前進 }',
    xpReward: 1500,
  },
  {
    id: 18,
    title: '4-3 記憶法術',
    description: '自訂 function 來封裝你的閃避邏輯。',
    player: { gridX: 1, gridY: 1, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 8, emoji: '👹', label: '雙角惡魔' },
    obstacles: [{ x: 3, y: 3 }, { x: 5, y: 5 }, { x: 7, y: 7 }],
    goals: ['定義自訂的 function', '讓主程式保持乾淨'],
    availableCommands: ['moveDown', 'moveRight', 'attack', 'while', 'function', 'isEnemyNear'],
    hint: '先定義 function dodge() { ... }，然後在 while 迴圈裡呼叫它！',
    xpReward: 1800,
  },
  {
    id: 19,
    title: '4-4 模組大軍',
    description: '多重函式與主程式的協作。',
    player: { gridX: 1, gridY: 8, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 1, emoji: '🌋', label: '熔岩巨獸' },
    obstacles: [{ x: 2, y: 7 }, { x: 4, y: 5 }, { x: 6, y: 3 }],
    goals: ['定義多個函式並互相呼叫'],
    availableCommands: ['moveUp', 'moveRight', 'attack', 'while', 'if', 'function', 'isEnemyNear', 'isObstacleAhead'],
    hint: '把「前進」、「閃避」、「攻擊」都寫成獨立的 function，這就是架構師的思維。',
    xpReward: 2000,
  },
  {
    id: 20,
    title: '4-5 傳奇自動化 (Final Boss)',
    description: '寫出一個能適應任何地形並自動過關的 AI。',
    player: { gridX: 1, gridY: 4, emoji: '🧙', label: '程式法師' },
    enemy:  { gridX: 8, gridY: 4, emoji: '👑', label: '深淵史萊姆魔王' },
    obstacles: [
      { x: 3, y: 4 }, { x: 4, y: 3 }, { x: 4, y: 5 }, { x: 6, y: 4 }
    ],
    restrictions: { hideDistance: true, maxBlocks: 15 },
    goals: ['結合所有學過的指令', '寫出完美的自動導航戰鬥腳本'],
    availableCommands: ['moveUp', 'moveDown', 'moveRight', 'moveLeft', 'attack', 'while', 'if', 'else', 'function', 'isEnemyNear', 'isObstacleAhead'],
    hint: '這是最終考驗！先設計好你的函式工具箱，再用一個完美的 while 迴圈迎戰吧！',
    xpReward: 3000,
    successMessage: '🏆 傳奇誕生！你已經完全掌握了程式邏輯，成為魔法程式之神！',
  }
];